"""empty message

Revision ID: 03399883bc9b
Revises: 4bf81d1da1d0
Create Date: 2017-04-11 09:07:20.944840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03399883bc9b'
down_revision = '4bf81d1da1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
