"""empty message

Revision ID: 046513147e8a
Revises: 1155a40ae942
Create Date: 2017-09-19 08:47:25.677043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046513147e8a'
down_revision = '1155a40ae942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
