"""empty message

Revision ID: 1155a40ae942
Revises: ecaecfaf3711
Create Date: 2017-09-18 22:25:42.366593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1155a40ae942'
down_revision = 'ecaecfaf3711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('binded', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'binded')
    # ### end Alembic commands ###
