"""empty message

Revision ID: 2d452c01aa81
Revises: f9110ed05ade
Create Date: 2017-09-22 08:52:00.326423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d452c01aa81'
down_revision = 'f9110ed05ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_name1'), 'categories', ['name1'], unique=False)
    op.create_index(op.f('ix_loginfo_ip'), 'loginfo', ['ip'], unique=False)
    op.create_index(op.f('ix_loginfo_url'), 'loginfo', ['url'], unique=False)
    op.create_index(op.f('ix_posts_sort_score'), 'posts', ['sort_score'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_styles_name'), 'styles', ['name'], unique=False)
    op.create_index(op.f('ix_styles_name1'), 'styles', ['name1'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_users_area'), 'users', ['area'], unique=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_county'), 'users', ['county'], unique=False)
    op.create_index(op.f('ix_users_ip_addr'), 'users', ['ip_addr'], unique=False)
    op.create_index(op.f('ix_users_post_total'), 'users', ['post_total'], unique=False)
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    op.create_unique_constraint(None, 'users', ['qq_id'])
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_index(op.f('ix_users_post_total'), table_name='users')
    op.drop_index(op.f('ix_users_ip_addr'), table_name='users')
    op.drop_index(op.f('ix_users_county'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_index(op.f('ix_users_area'), table_name='users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_styles_name1'), table_name='styles')
    op.drop_index(op.f('ix_styles_name'), table_name='styles')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_sort_score'), table_name='posts')
    op.drop_index(op.f('ix_loginfo_url'), table_name='loginfo')
    op.drop_index(op.f('ix_loginfo_ip'), table_name='loginfo')
    op.drop_index(op.f('ix_categories_name1'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###
