"""empty message

Revision ID: 33a44175850b
Revises: dd09268f74c2
Create Date: 2017-04-07 19:19:45.130748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a44175850b'
down_revision = 'dd09268f74c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_img', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_img')
    # ### end Alembic commands ###
