"""empty message

Revision ID: 36d28e436673
Revises: 6e4d0be8b763
Create Date: 2017-05-21 11:08:28.133328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36d28e436673'
down_revision = '6e4d0be8b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loginfo', sa.Column('time_r', sa.DateTime(), nullable=True))
    op.add_column('loginfo', sa.Column('time_stamp', sa.Integer(), nullable=True))
    op.drop_column('loginfo', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loginfo', sa.Column('time', mysql.DATETIME(), nullable=True))
    op.drop_column('loginfo', 'time_stamp')
    op.drop_column('loginfo', 'time_r')
    # ### end Alembic commands ###
