"""empty message

Revision ID: 3e37eed1b500
Revises: 40d3039a1e9f
Create Date: 2017-06-03 19:23:59.669908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e37eed1b500'
down_revision = '40d3039a1e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cate', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'cate')
    # ### end Alembic commands ###
