"""empty message

Revision ID: 45a25bf4804d
Revises: 2fdc586f5716
Create Date: 2017-09-25 07:45:44.765461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45a25bf4804d'
down_revision = '2fdc586f5716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('language', sa.String(length=30), nullable=True))
    op.drop_column('user_info', 'qq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('qq', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user_info', 'language')
    # ### end Alembic commands ###
