"""empty message

Revision ID: 556250efacf3
Revises: ca5e5a86c363
Create Date: 2017-09-18 21:21:53.197935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '556250efacf3'
down_revision = 'ca5e5a86c363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'open_id')
    op.add_column('users', sa.Column('open_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'open_id')
    op.add_column('posts', sa.Column('open_id', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
