"""empty message

Revision ID: 58a9f3d2911d
Revises: de83851c2f31
Create Date: 2017-05-24 14:07:39.637207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a9f3d2911d'
down_revision = 'de83851c2f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'area')
    # ### end Alembic commands ###
