"""empty message

Revision ID: 5ca81aa0c830
Revises: 556250efacf3
Create Date: 2017-09-18 22:23:03.117935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca81aa0c830'
down_revision = '556250efacf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('binded', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'binded')
    # ### end Alembic commands ###
