"""empty message

Revision ID: 6cc7794e2d78
Revises: fc1c03f86310
Create Date: 2017-02-18 11:41:16.025407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc7794e2d78'
down_revision = 'fc1c03f86310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name1', sa.String(length=30), nullable=True))
    op.add_column('styles', sa.Column('name1', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'name1')
    op.drop_column('categories', 'name1')
    # ### end Alembic commands ###
