"""empty message

Revision ID: 72b8b2133fd6
Revises: e5b771f2cf65
Create Date: 2017-06-04 10:26:05.305084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72b8b2133fd6'
down_revision = 'e5b771f2cf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cate', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('content', sa.String(length=3000), nullable=True))
    op.drop_column('messages', 'contents')
    op.drop_column('messages', 'cates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cates', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('contents', mysql.VARCHAR(length=3000), nullable=True))
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'cate')
    # ### end Alembic commands ###
