"""empty message

Revision ID: 9a3d13a85dc4
Revises: 2d452c01aa81
Create Date: 2017-09-24 12:16:28.883929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d13a85dc4'
down_revision = '2d452c01aa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('男', '女', '保密'), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('graduated', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('qq', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_categories_name1', table_name='categories')
    op.drop_index('ix_loginfo_ip', table_name='loginfo')
    op.drop_index('ix_loginfo_url', table_name='loginfo')
    op.drop_index('ix_posts_sort_score', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_index('ix_styles_name', table_name='styles')
    op.drop_index('ix_styles_name1', table_name='styles')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_index('github_id', table_name='users')
    op.drop_index('ix_users_area', table_name='users')
    op.drop_index('ix_users_city', table_name='users')
    op.drop_index('ix_users_country', table_name='users')
    op.drop_index('ix_users_county', table_name='users')
    op.drop_index('ix_users_ip_addr', table_name='users')
    op.drop_index('ix_users_post_total', table_name='users')
    op.drop_index('ix_users_region', table_name='users')
    op.drop_index('qq_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('qq_id', 'users', ['qq_id'], unique=True)
    op.create_index('ix_users_region', 'users', ['region'], unique=False)
    op.create_index('ix_users_post_total', 'users', ['post_total'], unique=False)
    op.create_index('ix_users_ip_addr', 'users', ['ip_addr'], unique=False)
    op.create_index('ix_users_county', 'users', ['county'], unique=False)
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_index('ix_users_city', 'users', ['city'], unique=False)
    op.create_index('ix_users_area', 'users', ['area'], unique=False)
    op.create_index('github_id', 'users', ['github_id'], unique=True)
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.create_index('ix_styles_name1', 'styles', ['name1'], unique=False)
    op.create_index('ix_styles_name', 'styles', ['name'], unique=False)
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_sort_score', 'posts', ['sort_score'], unique=False)
    op.create_index('ix_loginfo_url', 'loginfo', ['url'], unique=False)
    op.create_index('ix_loginfo_ip', 'loginfo', ['ip'], unique=False)
    op.create_index('ix_categories_name1', 'categories', ['name1'], unique=False)
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.drop_table('user_info')
    # ### end Alembic commands ###
