"""empty message

Revision ID: a72948974840
Revises: b1a89b5bf3d3
Create Date: 2017-09-15 01:44:13.613956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72948974840'
down_revision = 'b1a89b5bf3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'source')
    # ### end Alembic commands ###
