"""empty message

Revision ID: afb682102d4a
Revises: ad5ff7ee2a67
Create Date: 2017-02-18 10:09:18.668113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb682102d4a'
down_revision = 'ad5ff7ee2a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('postcategories', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postcategories', 'name')
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
