"""empty message

Revision ID: b1a89b5bf3d3
Revises: 72b8b2133fd6
Create Date: 2017-06-04 21:46:38.547558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a89b5bf3d3'
down_revision = '72b8b2133fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('sort_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sort_score')
    # ### end Alembic commands ###
