"""empty message

Revision ID: ba28af0d43e8
Revises: 680a8b2fcd9d
Create Date: 2017-04-06 20:24:43.977374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba28af0d43e8'
down_revision = '680a8b2fcd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collect', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collect', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collect', type_='foreignkey')
    op.drop_column('collect', 'post_id')
    # ### end Alembic commands ###
