"""empty message

Revision ID: bf7add479275
Revises: 074b004730f7
Create Date: 2017-05-31 20:37:37.990499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf7add479275'
down_revision = '074b004730f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('creat_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_replies_creat_at'), 'replies', ['creat_at'], unique=False)
    op.drop_index('ix_replies_created', table_name='replies')
    op.drop_column('replies', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.create_index('ix_replies_created', 'replies', ['created'], unique=False)
    op.drop_index(op.f('ix_replies_creat_at'), table_name='replies')
    op.drop_column('replies', 'creat_at')
    # ### end Alembic commands ###
