"""empty message

Revision ID: ca5e5a86c363
Revises: a72948974840
Create Date: 2017-09-18 21:19:25.943518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5e5a86c363'
down_revision = 'a72948974840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('open_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'open_id')
    # ### end Alembic commands ###
