"""empty message

Revision ID: d71d2b7968e3
Revises: 6e6f01b811ac
Create Date: 2017-04-20 00:59:26.879790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd71d2b7968e3'
down_revision = '6e6f01b811ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wx_num', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('zfb_num', sa.String(length=20), nullable=True))
    op.drop_column('users', 'wx_unm')
    op.drop_column('users', 'zfb_unm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zfb_unm', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('wx_unm', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'zfb_num')
    op.drop_column('users', 'wx_num')
    # ### end Alembic commands ###
