"""empty message

Revision ID: de83851c2f31
Revises: 36d28e436673
Create Date: 2017-05-24 14:01:05.838378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de83851c2f31'
down_revision = '36d28e436673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('county', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('ip_addr', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    op.drop_column('users', 'ip_addr')
    op.drop_column('users', 'county')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
