"""empty message

Revision ID: e2045b147134
Revises: 58a9f3d2911d
Create Date: 2017-05-27 15:51:47.530114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2045b147134'
down_revision = '58a9f3d2911d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_public')
    # ### end Alembic commands ###
