"""empty message

Revision ID: e5b771f2cf65
Revises: d3717190b66f
Create Date: 2017-06-04 10:25:05.636017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5b771f2cf65'
down_revision = 'd3717190b66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cates', sa.Integer(), nullable=True))
    op.drop_column('messages', 'cate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cate', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('messages', 'cates')
    # ### end Alembic commands ###
