"""empty message

Revision ID: f9110ed05ade
Revises: 046513147e8a
Create Date: 2017-09-20 23:48:01.115517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9110ed05ade'
down_revision = '046513147e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qq_id', sa.String(length=100), nullable=True))
    op.drop_column('users', 'open_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('open_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'qq_id')
    # ### end Alembic commands ###
