"""empty message

Revision ID: fc1c03f86310
Revises: fa281a4e98f4
Create Date: 2017-02-18 11:11:44.805563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1c03f86310'
down_revision = 'fa281a4e98f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('style', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'style')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
